name: CI-BUILD

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
    
jobs:
  build:

    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: 'MySolution.sln'

    runs-on: ubuntu-latest

    steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'
        dotnet-quality: 'ga'

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1

    - name: Configure git
      run: git config --global user.email "ci-runner@example.com" && git config --global user.name "CI Runner"
      
    - run: sudo apt install p7zip
    
    - run: which 7z

    - name: Check out source
      uses: actions/checkout@v3

    - name: Build Nuget Package
      run: cd main && nuget pack -Properties NoWarn=NU5100 nsis.nuspec

    - run: ls -la

    - name: Check in the result
      run: git add . && git commit -m "Checking in nuget"

    - name: Push
      run: git push


#    - name: Restore dependencies
#      run: nuget restore $SOLUTION


#    - name: Build
#      run: dotnet build $SOLUTION --configuration $BUILD_CONFIG --no-restore

#    - name: Run tests
#      run: dotnet test /p:Configuration=$env:BUILD_CONFIG --no-restore --no-build --verbosity normal